name: Pull CSV from Google Sheets

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight. Change as needed.
  workflow_dispatch: # Allows manual trigger from the Actions tab.

jobs:
  download-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download Google Sheet as CSV
        run: |
          curl -L -o movies.csv "https://docs.google.com/spreadsheets/d/1d34tKIHhvrtr1XP4iEjRDZrxMYpmwr7b123JzaOyyWo/export?format=csv&gid=991143387"

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add movies.csv
          git diff-index --quiet HEAD || git commit -m "Automated update of data.csv"
          git push
